// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.data.migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240224185423_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Entities.Spot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("April")
                        .HasColumnType("bit");

                    b.Property<bool>("August")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("December")
                        .HasColumnType("bit");

                    b.Property<int>("Description")
                        .HasColumnType("int");

                    b.Property<bool>("February")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdvanced")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBeginner")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIntermediate")
                        .HasColumnType("bit");

                    b.Property<bool>("January")
                        .HasColumnType("bit");

                    b.Property<bool>("July")
                        .HasColumnType("bit");

                    b.Property<bool>("June")
                        .HasColumnType("bit");

                    b.Property<bool>("March")
                        .HasColumnType("bit");

                    b.Property<bool>("May")
                        .HasColumnType("bit");

                    b.Property<bool>("November")
                        .HasColumnType("bit");

                    b.Property<bool>("October")
                        .HasColumnType("bit");

                    b.Property<bool>("September")
                        .HasColumnType("bit");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spots");
                });
#pragma warning restore 612, 618
        }
    }
}
